title = "Basic"

[[entries]]
title = "test"
files = ["test.sh"]

[[entries]]
title = "pai"
files = ["pai.sh"]

[[entries]]
title = "run"
files = ["run.sh"]

[[entries]]
title = "缺省源"
files = ["src.cpp"]

[[entries]]
title = "随机数"
files = ["random.cpp"]

[[entries]]
title = "Matrix"
files = ["matrix.cpp"]
