title = "Data Structure"

[[entries]]
title = "可撤销并查集"
files = ["rollback_dsu.md", "rollback_dsu.cpp"]

[[entries]]
title = "单点修改线段树"
files = ["sgt.md", "sgt.cpp", "sgt_usage.cpp"]

[[entries]]
title = "区间修改线段树"
files = ["lazy_sgt.md", "lazy_sgt.cpp", "lazy_sgt_usage.cpp"]

[[entries]]
title = "线段树二分"
files = ["sgt_bisect.md", "sgt_bisect.cpp"]

[[entries]]
title = "可持久化线段树/动态开点"
files = [
  "persistent_sgt.md",
  "persistent_sgt.cpp",
  "persistent_sgt_usage.cpp",
  "dynamic_sgt.md",
  "dynamic_sgt.cpp",
]

[[entries]]
title = "李超树"
files = ["li_chao.md", "li_chao.cpp"]

[[entries]]
title = "线段树合并/分裂"
files = ["segment_tree_merge_split.md", "segment_tree_merge_split.cpp"]

[[entries]]
title = "ODT"
files = ["odt.cpp", "odt_usage.cpp"]

[[entries]]
title = "FHQ Treap"
files = ["fhq_treap.cpp", "fhq_treap_usage.cpp"]

[[entries]]
title = "pbds tree"
files = ["pbds_tree.md", "pbds_tree.cpp"]

[[entries]]
title = "普通莫队"
files = ["mo.md", "mo.cpp"]

[[entries]]
title = "带修莫队"
files = ["mo_modify.md", "mo_modify.cpp"]

[[entries]]
title = "回滚莫队"
files = ["mo_rollback.md", "mo_rollback.cpp"]

[[entries]]
title = "莫队二次离线"
files = ["mo_secondary_offline.md", "mo_secondary_offline.cpp"]
