title = "Data Structure"

[[entries]]
title = "单点修改线段树"
files = ["sgt.md", "sgt.cpp", "sgt_usage.cpp"]

[[entries]]
title = "区间修改线段树"
files = ["lazy_sgt.md", "lazy_sgt.cpp", "lazy_sgt_usage.cpp"]

[[entries]]
title = "线段树二分"
files = ["sgt_bisect.md", "sgt_bisect.cpp"]

[[entries]]
title = "可持久化线段树/动态开点"
files = [
  "persistent_sgt.md",
  "persistent_sgt.cpp",
  "persistent_sgt_usage.cpp",
  "dynamic_sgt.md",
  "dynamic_sgt.cpp",
]

[[entries]]
title = "李超树"
files = ["li_chao.md", "li_chao.cpp"]

[[entries]]
title = "线段树合并/分裂"
files = ["segment_tree_merge_split.md", "segment_tree_merge_split.cpp"]

[[entries]]
title = "历史操作"
files = [
  "historical.md",
  "historical_min_count.cpp",
  "historical_min_count_usage.cpp",
]
