title = "Math"

[[entries]]
title = "ExGCD"
files = ["exgcd.md", "exgcd.cpp"]

[[entries]]
title = "BSGS / ExBSGS"
files = ["exbsgs.md", "exbsgs.cpp"]

[[entries]]
title = "线性筛"
files = ["sieve.md", "sieve.cpp"]

[[entries]]
title = "Miller-Rabin / Pollard-Rho"
files = ["factor.md", "factor.cpp"]

[[entries]]
title = "Primitive Root"
files = ["primitive_root.md", "primitive_root.cpp"]

[[entries]]
title = "exCRT"
files = ["crt.md", "crt.cpp"]

[[entries]]
title = "二次剩余"
files = ["tonelli_shanks.md", "tonelli_shanks.cpp"]

[[entries]]
title = "floor sum"
files = ["floor_sum.md", "floor_sum.cpp"]

[[entries]]
title = "万欧"
files = ["universal_euclid.md", "universal_euclid.cpp"]

[[entries]]
title = "杜教筛"
files = ["du_sieve.md", "du_sieve.cpp"]

[[entries]]
title = "Min_25 筛"
files = ["min25.md", "min25.cpp"]

[[entries]]
title = "ExLucas"
files = ["exlucas.md", "exlucas.cpp"]

[[entries]]
title = "容斥反演"
files = ["inclusion_exclusion.md"]
