title = "Misc"

[[entries]]
title = "模拟退火"
files = ["annealing.cpp"]

[[entries]]
title = "爬山法"
files = ["hill_climbing.cpp"]

[[entries]]
title = "高精度"
files = ["bigint.md", "bigint.cpp"]

[[entries]]
title = "手写 bitset"
files = ["bitset.md", "bitset.cpp"]

[[entries]]
title = "常数表"
files = ["constants.md"]
wide = true
