title = "Number Theory"

[[entries]]
title = "ModInt"
files = ["modint.md", "modint.cpp"]

[[entries]]
title = "Extended GCD"
files = ["exgcd.md", "exgcd.cpp"]

[[entries]]
title = "CRT"
files = ["crt.md", "crt.cpp"]

[[entries]]
title = "Linear Sieve"
files = ["sieve.md", "sieve.cpp"]

[[entries]]
title = "Miller-Rabin / Pollard-Rho"
files = ["factor.md", "factor.cpp"]

[[entries]]
title = "Primitive Root"
files = ["primitive_root.md", "primitive_root.cpp"]

[[entries]]
title = "exBSGS"
files = ["exbsgs.md", "exbsgs.cpp"]

[[entries]]
title = "Tonelli-Shanks"
files = ["tonelli_shanks.md", "tonelli_shanks.cpp"]
